#:schema node_modules/wrangler/config-schema.json
name = "genshin-statistical-manager"
main = "src/index.ts"
compatibility_date = "2024-11-12"
# compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [ "0 */8 * * *", "0 1-7,9-15,17-23 * * *" ]

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
[vars]
PLAYER_LIMIT = 100000 #50000
CHARACTER_LIMIT = 25000 #10000
DAY_LIMIT = 365 #100

# https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[ d1_databases ]]
binding = "db"
database_name = "genshin-statistical-sources"
database_id = "ecd6e443-de93-48b2-8d30-038e2613bf95"

# https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
# [[ kv_namespaces ]]
# binding = "kv"
# id = "45c070da16fc4324a71bbc6b390c4235"
# preview_id = "genshin-cache"
